version: "3.9"
services:

  mocksensor:
    build: mocksensor
    container_name: 07-inducode-mocksensor
    restart: always
    networks:
      - 00-infraestructura_dockers_net
    volumes:
      - ./data/mocksensor:/tmp/
  
  emqx:
    user: root
    image: "emqx:5.8.0"
    container_name: 07-inducode-emqx
    restart: always
    networks:
      - 00-infraestructura_dockers_net
    ports:
      - "18083:18083"
      - "1883:1883"
      - "4369:4369"
    volumes:
      - ./data/emqx/data:/opt/emqx/data
      - ./data/emqx/log:/opt/emqx/log
    environment:
      EMQX_DASHBOARD__DEFAULT_USER__LOGIN: inducodeadmin
      EMQX_DASHBOARD__DEFAULT_USER__PASSWORD: iotinducore
      # Letsencrypt config
      VIRTUAL_HOST: mqtt.inducode.com.ar
      LETSENCRYPT_HOST: mqtt.inducode.com.ar
      LETSENCRYPT_EMAIL: carlos@sauay.com
  
  telegrafinput:
    image: "telegraf:1.32"
    container_name: 07-inducode-telegrafinput
    restart: always
    networks:
      - 00-infraestructura_dockers_net
    volumes:
      - ./data/telegrafinput/telegraf.conf:/etc/telegraf/telegraf.conf
      - ./data/mocksensor:/tmp/mocksensor
  
  influxdb:
    image: "influxdb:2.7"
    container_name: 07-inducode-influxdb
    restart: always
    networks:
      - 00-infraestructura_dockers_net
    ports: 
      - "8086:8086"
    volumes:
      - ./data/influxdb/data:/var/lib/influxdb2
      - ./data/influxdb/config:/etc/influxdb2
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME: inducodeadmin
      DOCKER_INFLUXDB_INIT_PASSWORD: iotinducode
      DOCKER_INFLUXDB_INIT_ORG: inducode
      DOCKER_INFLUXDB_INIT_BUCKET: iotdata
      DOCKER_INFLUXDB_INIT_RETENTION: 1w
      #echo -n '{"sub":"inducodeadmin","name":"InduCode","admin":true}' | openssl base64 | tr -d '=' | tr '/+' '_-'
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: eyJzdWIiOiJpbmR1Y29kZWFkbWluIiwibmFtZSI6IkluZHVDb2RlIiwiYWRtaW4iOnRydWV9
      # Letsencrypt config
      VIRTUAL_HOST: influxdb.inducode.com.ar
      LETSENCRYPT_HOST: influxdb.inducode.com.ar
      LETSENCRYPT_EMAIL: carlos@sauay.com
  
  telegrafoutput:
    image: "telegraf:1.22.4"
    container_name: 07-inducode-telegrafoutput
    restart: always
    networks:
      - 00-infraestructura_dockers_net
    # deploy:
    #   restart_policy:
    #     condition: on-failure
    #     delay: 10s
    #     max_attempts: 20
    volumes:
      - ./data/telegrafoutput/telegraf.conf:/etc/telegraf/telegraf.conf
  
  grafana:
    user: root
    image: "grafana/grafana:11.2.0"
    container_name: 07-inducode-grafana
    restart: always
    networks:
      - 00-infraestructura_dockers_net
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD__FILE: /run/secrets/admin_password
      # Letsencrypt config
      VIRTUAL_HOST: dashboard.inducode.com.ar
      LETSENCRYPT_HOST: dashboard.inducode.com.ar
      LETSENCRYPT_EMAIL: carlos@sauay.com
    volumes:
      - ./data/grafana:/var/lib/grafana
    secrets:
      - source: grafana_admin_password
        target: /run/secrets/admin_password

secrets:
  grafana_admin_password:
    file: ./secrets/grafana_admin_password

networks:
    00-infraestructura_dockers_net:
        external: true
